name: Build and Publish Add-ons

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, armv7, aarch64]
        addon: [voyanti-pace]  # List all add-ons you want to build

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Check for specific build conditions (optional)
      - name: Check for architecture and conditions
        id: check
        run: echo "::set-output name=build_arch::true"

      # Step 5: Build the Home Assistant add-on
      - name: Build ${{ matrix.addon }} add-on
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder@2024.08.2
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --image "ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon

      # Step 6: Push the built image to GitHub Container Registry (GHCR)
      - name: Push the image
        if: steps.check.outputs.build_arch == 'true'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}:${{ matrix.arch }}